# DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.184:5432/postgres
    username: postgres
    password: nicom123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create