# DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.184:5432/postgres
    username: postgres
    password: nicom123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
#      ddl-auto: create


#      datasource:
#        url: jdbc:postgresql://127.0.0.1:5432/EZBoard
#        username: postgres
#        password: nicom123.

#      url: jdbc:postgresql://192.168.0.184:5432/postgres
#      username: postgres
#      password: nicom123