spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active:
      - postgresql
  datasource:
    hikari:
      maximum-pool-size: 1
      auto-commit: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
# Server Configuration
server:
  port: 9000

# logging:
  # level:
    # root: DEBUG
system:
  name: Kyoritsu
  version: 1.0.0
  # 시스템 관리자 초기 비밀번호
  initPwd: nicom123.
